/**
 * {{NAME}}: an API provider. Generated by `npm run provider:new`; its manifest is in
 * `manifest.ts`, its raw shapes and mapping in `mapping.ts`.
 *
 * TODO before it ships:
 * - Read {{NAME}}'s terms of use and note here what they say about automated access.
 * - Set {{CONST}}_API_URL and {{CONST}}_SITE_URL below.
 * - Replace the request paths and parameters below, and the raw shapes in `mapping.ts`, with
 *   the real API's.
 * - Replace the sample responses in `tests/fixtures/providers/{{ID}}/` and
 *   `tests/e2e/fixtures/http/{{ID}}/` with real ones: public, recorded without signing in,
 *   trimmed, and with no personal details.
 *
 * Until the addresses are set, every call fails with a ProviderError that says so, nothing is
 * sent anywhere, and the provider has no links.
 */

import type { LocationDetail } from '@shared/types/catalog.types';
import type { LocationAvailability } from '@shared/types/provider.types';
import { makeLocationKey } from '@shared/utils/location-key';
import {
  createLimiter,
  defineProvider,
  ProviderError,
// @if search
  type CatalogAreaPage,
// @endif
  type ProviderContext,
  type ProviderFactory,
  type ProviderLinks,
} from '../sdk';
import { {{CAMEL}}Manifest } from './manifest';
import {
// @if search
  isInside,
// @endif
  parseRaw,
  RawAvailability,
  RawLocationDetail,
// @if search
  RawSearchPage,
// @else
  RawLocationList,
// @endif
  toLocationSummary,
  toUnitAvailability,
  toUnitSummary,
} from './mapping';

export { {{CAMEL}}Manifest } from './manifest';

/** TODO: the API's https address, such as `https://api.example.com`. */
export const {{CONST}}_API_URL = '';
/** TODO: the provider's public website, for links to its pages. */
export const {{CONST}}_SITE_URL = '';

export interface {{PASCAL}}Options {
  /** The API's address: {{CONST}}_API_URL unless a test gives another. */
  apiUrl?: string;
  /** The website's address, for links: {{CONST}}_SITE_URL unless a test gives another. */
  siteUrl?: string;
}

export function create{{PASCAL}}Factory({
  apiUrl = {{CONST}}_API_URL,
  siteUrl = {{CONST}}_SITE_URL,
}: {{PASCAL}}Options = {}): ProviderFactory {
  return defineProvider({{CAMEL}}Manifest, (ctx: ProviderContext) => {
    // Every request asks for JSON, and no more are in flight than the manifest allows.
    const http = ctx.http.withDefaults({ headers: { Accept: 'application/json' } });
    const limit = createLimiter(ctx.limits.maxConcurrentRequests);

    /**
     * The JSON at `path` on the API. A non-2xx answer rejects with a ProviderHttpError, a body
     * that is not JSON with a ProviderParseError, and an abort with an AbortError. While the
     * API's address is a placeholder it rejects at once and sends nothing.
     */
    async function get(
      path: string,
      query: Record<string, string | number>,
      signal?: AbortSignal
    ): Promise<unknown> {
      if (!apiUrl) {
        throw new ProviderError({
          providerId: ctx.id,
          message: `${ctx.manifest.name} is not set up yet: set {{CONST}}_API_URL in src/main/providers/{{ID}}/index.ts`,
        });
      }
      const url = `${apiUrl.replace(/\/+$/, '')}${path}`;
      return limit(() => http.getJson<unknown>(url, { query, signal }));
    }

    /** A page of the provider's website, or null while its address is a placeholder. */
    const sitePage = (path: string): string | null =>
      siteUrl ? `${siteUrl.replace(/\/+$/, '')}${path}` : null;

    const links: ProviderLinks = {
      // TODO: the provider's own page for a place, and its booking page (with the stay's dates
      // when it takes them).
      location: (externalId) => sitePage(`/places/${encodeURIComponent(externalId)}`),
      booking: (externalId, stay) =>
        sitePage(
          `/book/${encodeURIComponent(externalId)}` +
            (stay ? `?${new URLSearchParams({ arrival: stay.arrival, departure: stay.departure })}` : '')
        ),
    };

    return {
      links,
      catalog: {
// @if search
        // TODO: the API's search by map area. One results page per call: the app follows
        // `nextCursor` for a few pages, and keeps what it finds.
        async searchArea({ bbox, cursor }, signal): Promise<CatalogAreaPage> {
          const [west, south, east, north] = bbox;
          // The cursor is the API's page number, as a string; the first page has none.
          const page = cursor ? Number(cursor) : 1;
          const body = await get('/search', { west, south, east, north, page }, signal);
          const raw = parseRaw(ctx.id, '/search', RawSearchPage, body);
          const items = raw.locations
            // Only the places inside the area, whatever the API sends.
            .filter((location) => isInside(bbox, location))
            .map((location) => toLocationSummary(ctx.id, location, links));
          return raw.nextPage ? { items, nextCursor: String(raw.nextPage) } : { items };
        },
        // Optional: the API's search by name, for a name someone types into Explore's "Where"
        // or a watch's location step (3 characters or more). One request, the best few dozen
        // matches. If the API cannot search by name, delete it: the location step then
        // suggests browsing the provider's places on the Explore map instead.
        async searchText(text, signal) {
          const raw = parseRaw(ctx.id, '/find', RawSearchPage, await get('/find', { text }, signal));
          return raw.locations.map((location) => toLocationSummary(ctx.id, location, links));
        },
// @else
        // TODO: the API's list of every place.
        async listLocations(signal) {
          const raw = parseRaw(ctx.id, '/locations', RawLocationList, await get('/locations', {}, signal));
          return raw.locations.map((location) => toLocationSummary(ctx.id, location, links));
        },
// @endif
        // TODO: the API's detail of one place, with its units.
        async getLocation(externalId, signal): Promise<LocationDetail> {
          const path = `/locations/${encodeURIComponent(externalId)}`;
          const raw = parseRaw(ctx.id, path, RawLocationDetail, await get(path, {}, signal));
          return {
            ...toLocationSummary(ctx.id, raw, links),
            // Raw provider HTML: main sanitises it before it crosses to the renderer.
            descriptionHtml: raw.description,
            units: raw.units.map(toUnitSummary),
            fetchedAt: ctx.clock().toISOString(),
          };
        },
      },
      availability: {
        // TODO: the API's availability for one place and stay.
        async check(externalId, stay, options = {}): Promise<LocationAvailability> {
          const path = `/locations/${encodeURIComponent(externalId)}/availability`;
          const query = {
            arrival: stay.arrival,
            departure: stay.departure,
            guests: stay.adults + (stay.children ?? 0),
          };
          const raw = parseRaw(ctx.id, path, RawAvailability, await get(path, query, options.signal));
          const wanted = options.unitIds?.length ? new Set(options.unitIds) : undefined;
          return {
            key: makeLocationKey(ctx.id, externalId),
            checkedAt: ctx.clock().toISOString(),
            units: raw.units
              .filter((unit) => !wanted || wanted.has(unit.id))
              .map((unit) => toUnitAvailability(stay, unit)),
            bookingUrl: links.booking(externalId, stay) ?? undefined,
          };
        },
      },
    };
  });
}

/** What `BUILT_IN_PROVIDERS` in `src/main/providers/index.ts` registers. */
export const {{CAMEL}}Factory = create{{PASCAL}}Factory();
