/**
 * {{NAME}} (`src/main/providers/{{ID}}/`): the provider contract suite and the mapping, on the
 * recorded responses in `tests/fixtures/providers/{{ID}}/`. A FixtureHttpClient serves them by
 * request path, so nothing is sent anywhere.
 *
 * Generated by `npm run provider:new`. Keep it passing as the module grows, and replace the
 * sample responses (and the expectations below) with the real API's.
 */

import fs from 'fs';
import os from 'os';
import path from 'path';
import { ProviderHttpError } from '@main/providers/sdk';
import { ProviderRegistry } from '@main/providers/registry';
import { FixtureHttpClient } from '@main/testing/fixture-http-client';
// @if search
import type { BoundingBox } from '@shared/types/catalog.types';
// @endif
import { isCalendarDate, type StayQuery } from '@shared/types/provider.types';
import { createTestProviderContext } from '@tests/utils/fake-provider';
import { describeProviderContract } from '@tests/utils/provider-contract';
import {
  {{CONST}}_API_URL,
  {{CONST}}_SITE_URL,
  create{{PASCAL}}Factory,
  {{CAMEL}}Manifest,
} from '@main/providers/{{ID}}';

/** Holds `{{ID}}/manifest.json`, which lists the recorded responses by request path. */
const FIXTURES_DIR = path.join(__dirname, '../fixtures/providers');
/** Where a FixtureHttpClient logs a request that no fixture answers (it fails, unsent). */
const UNEXPECTED_LOG = path.join(os.tmpdir(), `{{ID}}-unexpected-${process.pid}.log`);
/** Any https addresses do: a FixtureHttpClient answers by path and never sends anything. */
const API_URL = 'https://api.{{ID}}.test';
const SITE_URL = 'https://www.{{ID}}.test';
const STAY: StayQuery = { arrival: '2026-11-10', departure: '2026-11-12', adults: 2 };
// @if search
/** Western Australia, `[west, south, east, north]`. */
const WA: BoundingBox = [112, -36, 129, -13];
// @endif

/** A test context (in-memory state, a fixed clock) whose HTTP answers from the fixtures. */
function fixtureContext(logFile = UNEXPECTED_LOG) {
  return createTestProviderContext({{CAMEL}}Manifest, {
    http: new FixtureHttpClient({ providerId: '{{ID}}', fixturesDir: FIXTURES_DIR, logFile }),
  });
}

afterAll(() => fs.rmSync(UNEXPECTED_LOG, { force: true }));

describeProviderContract('{{ID}}', () => {
  const factory = create{{PASCAL}}Factory({ apiUrl: API_URL, siteUrl: SITE_URL });
  return {
    provider: factory(fixtureContext()),
    sample: { externalId: '1001', stay: STAY },
    unknownExternalId: 'does-not-exist',
// @if search
    searchBbox: WA,
    searchText: 'Banksia',
// @endif
  };
});

describe('{{NAME_JS}}', () => {
  // Registered in a fresh registry, as the app registers it.
  const registry = new ProviderRegistry();
  registry.register(create{{PASCAL}}Factory({ apiUrl: API_URL, siteUrl: SITE_URL }), () =>
    fixtureContext()
  );
  const provider = registry.require('{{ID}}', 'availability');

// @if search
  it('searches a map area a page at a time, and keeps only the places inside it', async () => {
    const first = await provider.catalog!.searchArea!({ bbox: WA });
    expect(first.items).toEqual([
      expect.objectContaining({
        key: '{{ID}}:1001',
        providerId: '{{ID}}',
        externalId: '1001',
        name: 'Banksia Flat Campground',
        kind: 'campground',
        bookingMode: 'online',
        lat: -33.9536,
        lng: 115.0726,
        area: { name: 'Margaret River', region: 'South West' },
        // The http photo is left out: images must be https.
        imageUrls: ['https://images.{{ID}}.invalid/1001.jpg'],
        amenities: ['Toilets', 'Fire pits'],
        infoUrl: `${SITE_URL}/places/1001`,
      }),
      expect.objectContaining({ key: '{{ID}}:1002', kind: 'cabin' }),
    ]);
    expect(first.nextCursor).toBe('2');

    const second = await provider.catalog!.searchArea!({ bbox: WA, cursor: first.nextCursor });
    // A word the mapping does not know is `other`; 1004, in Sydney, is outside the area and left out.
    expect(second.items).toEqual([expect.objectContaining({ key: '{{ID}}:1003', kind: 'other' })]);
    expect(second.nextCursor).toBeUndefined();
  });

  it('searches by name', async () => {
    await expect(provider.catalog!.searchText!('Banksia')).resolves.toEqual([
      expect.objectContaining({ key: '{{ID}}:1001', name: 'Banksia Flat Campground' }),
    ]);
  });
// @else
  it('lists every place as a LocationSummary: key, kind, coordinates, https photos', async () => {
    await expect(provider.catalog!.listLocations!()).resolves.toEqual([
      expect.objectContaining({
        key: '{{ID}}:1001',
        providerId: '{{ID}}',
        externalId: '1001',
        name: 'Banksia Flat Campground',
        kind: 'campground',
        bookingMode: 'online',
        lat: -33.9536,
        lng: 115.0726,
        area: { name: 'Margaret River', region: 'South West' },
        // The http photo is left out: images must be https.
        imageUrls: ['https://images.{{ID}}.invalid/1001.jpg'],
        amenities: ['Toilets', 'Fire pits'],
        infoUrl: `${SITE_URL}/places/1001`,
      }),
      expect.objectContaining({ key: '{{ID}}:1002', kind: 'cabin' }),
      // A word the mapping does not know is `other`.
      expect.objectContaining({ key: '{{ID}}:1003', kind: 'other' }),
    ]);
  });
// @endif

  it("builds a place's detail: its units, and the raw description for main to sanitise", async () => {
    await expect(provider.catalog!.getLocation('1001')).resolves.toMatchObject({
      key: '{{ID}}:1001',
      descriptionHtml: '<p>Shady sites under the banksias, a short walk from the river.</p>',
      units: [
        { unitId: 's1', unitName: 'Site 1', unitType: 'Powered', maxPeople: 6 },
        { unitId: 's2', unitName: 'Site 2', unitType: 'Unpowered', maxPeople: 4 },
        { unitId: 's3', unitName: 'Site 3' },
      ],
    });
  });

  it('answers a stay night by night: only its nights, as YYYY-MM-DD, never guessing', async () => {
    const result = await provider.availability.check('1001', STAY);
    expect(result.key).toBe('{{ID}}:1001');
    expect(result.units).toEqual([
      {
        unitId: 's1',
        unitName: 'Site 1',
        nights: [
          { date: '2026-11-10', state: 'available', price: 42 },
          { date: '2026-11-11', state: 'available', price: 45 },
        ],
        fullyAvailable: true,
        total: 87,
      },
      {
        unitId: 's2',
        unitName: 'Site 2',
        nights: [
          { date: '2026-11-10', state: 'available', price: 30 },
          { date: '2026-11-11', state: 'booked' },
        ],
        fullyAvailable: false,
      },
      {
        // A word the mapping does not know is `unknown`, and so is a night the API left out.
        unitId: 's3',
        unitName: 'Site 3',
        nights: [
          { date: '2026-11-10', state: 'unknown' },
          { date: '2026-11-11', state: 'unknown' },
        ],
        fullyAvailable: false,
      },
    ]);
    for (const night of result.units.flatMap((unit) => unit.nights)) {
      expect(isCalendarDate(night.date)).toBe(true);
    }
    expect(result.bookingUrl).toBe(`${SITE_URL}/book/1001?arrival=2026-11-10&departure=2026-11-12`);
  });

  it('keeps only the units asked for', async () => {
    const result = await provider.availability.check('1001', STAY, { unitIds: ['s2'] });
    expect(result.units.map((unit) => unit.unitId)).toEqual(['s2']);
  });

  it('rejects a place the API does not know with a ProviderHttpError', async () => {
    await expect(provider.catalog!.getLocation('does-not-exist')).rejects.toBeInstanceOf(
      ProviderHttpError
    );
  });

  it('has https addresses, or fails loudly and sends nothing while they are placeholders', async () => {
    if ({{CONST}}_API_URL || {{CONST}}_SITE_URL) {
      expect({{CONST}}_API_URL).toMatch(/^https:\/\//);
      expect({{CONST}}_SITE_URL).toMatch(/^https:\/\//);
      return;
    }
    const log = path.join(os.tmpdir(), `{{ID}}-placeholders-${process.pid}.log`);
    const unset = create{{PASCAL}}Factory()(fixtureContext(log));
    await expect(unset.catalog!.getLocation('1001')).rejects.toThrow(/set {{CONST}}_API_URL/);
    expect(unset.links.location('1001')).toBeNull();
    expect(fs.existsSync(log)).toBe(false);
  });
});
