/**
 * A made-up copy of {{NAME}}'s website, for the fake browser (`tests/utils/fake-browser.ts`):
 * the pages, the place page's search form and the script that draws its results, in the markup
 * `src/main/providers/{{ID}}/pages.ts` reads. The fake loads it into jsdom and runs its
 * script, so the provider's own page code runs against it.
 *
 * Generated by `npm run provider:new`. TODO: replace it with a trimmed copy of the real site's
 * markup (its attributes, labels and words), with no personal details.
 */

import type { FakeRoute } from '@tests/utils/fake-browser';

interface Place {
  id: string;
  kind: string;
  name: string;
  town: string;
  lat: number;
  lng: number;
  units: { id: string; name: string; nights: Record<string, [status: string, label: string]> }[];
}

const PLACES: Place[] = [
  {
    id: 'beach-house',
    kind: 'holiday',
    name: 'Seabreeze Holiday Park',
    town: 'Busselton',
    lat: -33.6455,
    lng: 115.3459,
    units: [
      {
        id: 'c1',
        name: 'Beach Cabin 1',
        nights: {
          '2026-11-09': ['vacant', '$150.00'],
          '2026-11-10': ['vacant', '$145.00'],
          '2026-11-11': ['vacant', '$155.00'],
        },
      },
      {
        id: 'c2',
        name: 'Garden Cabin 2',
        nights: { '2026-11-10': ['booked', 'Booked'], '2026-11-11': ['vacant', '$120.00'] },
      },
      { id: 'c3', name: 'Bunkhouse', nights: { '2026-11-10': ['held', 'On hold'] } },
    ],
  },
  {
    id: 'karri-cabins',
    kind: 'cabin',
    name: 'Karri Valley Cabins',
    town: 'Pemberton',
    lat: -34.4471,
    lng: 116.0322,
    units: [{ id: 'k1', name: 'Karri Cabin', nights: { '2026-11-10': ['closed', 'Closed'] } }],
  },
  {
    id: 'old-mill',
    kind: 'farmstay',
    name: 'Old Mill Farm Stay',
    town: 'Bridgetown',
    lat: -33.9572,
    lng: 116.1366,
    units: [],
  },
];

/** The place page's script: on submit it asks the site for the nights and draws a table. */
const SEARCH_SCRIPT = `
  const form = document.querySelector('form[data-search]');
  form.addEventListener('submit', async (event) => {
    event.preventDefault();
    const query = new URLSearchParams({
      place: form.elements.place.value,
      arrival: form.elements.arrival.value,
      departure: form.elements.departure.value,
      guests: form.elements.guests.value,
    });
    const { units } = await (await fetch('/api/availability?' + query)).json();
    const rows = units.map((unit) =>
      '<tr data-unit="' + unit.id + '" data-unit-name="' + unit.name + '"><th>' + unit.name + '</th>' +
      unit.nights
        .map((n) => '<td data-night="' + n.date + '" data-status="' + n.status + '">' + n.label + '</td>')
        .join('') +
      '</tr>'
    );
    const results = document.querySelector('[data-results]');
    results.querySelector('tbody').innerHTML = rows.join('');
    results.hidden = false;
  });
`;

function html(title: string, body: string, status = 200): FakeRoute {
  return {
    status,
    body: `<!doctype html><html><head><title>${title} | {{NAME_HTML}}</title></head><body>${body}</body></html>`,
  };
}

function placeAttributes(place: Place): string {
  return `data-place="${place.id}" data-kind="${place.kind}" data-lat="${place.lat}" data-lng="${place.lng}"`;
}

function listItems(places: Place[]): string {
  return places
    .map(
      (place) =>
        `<li ${placeAttributes(place)}><a href="/places/${place.id}" data-testid="name">${place.name}</a>` +
        `<span data-testid="town">${place.town}</span></li>`
    )
    .join('');
}

function placePage(place: Place): FakeRoute {
  const units = place.units.map((unit) => `<li data-unit="${unit.id}">${unit.name}</li>`);
  return html(
    place.name,
    `<main ${placeAttributes(place)}>
      <h1 data-testid="name">${place.name}</h1>
      <p data-testid="town">${place.town}</p>
      <ul>${units.join('')}</ul>
      <form data-search>
        <input type="hidden" name="place" value="${place.id}">
        <label>Arrival <input type="date" name="arrival"></label>
        <label>Departure <input type="date" name="departure"></label>
        <label>Guests <input type="number" name="guests" value="2" min="1"></label>
        <button type="submit">Check availability</button>
      </form>
      <section data-results hidden><h2>Availability</h2><table><tbody></tbody></table></section>
      <script>${SEARCH_SCRIPT}</script>
    </main>`
  );
}

/** What the place page's script fetches: every night the site knows, whatever the stay. */
function availability(placeId: string | null): FakeRoute {
  const place = PLACES.find((p) => p.id === placeId);
  if (!place) return { status: 404, headers: { 'content-type': 'application/json' }, body: '{}' };
  const units = place.units.map((unit) => ({
    id: unit.id,
    name: unit.name,
    nights: Object.entries(unit.nights).map(([date, [status, label]]) => ({ date, status, label })),
  }));
  return { headers: { 'content-type': 'application/json' }, body: JSON.stringify({ units }) };
}
// @if search

/**
 * The search page: the places whose name has `text` in it, or else the places inside `west`,
 * `south`, `east`, `north`, two to a page.
 */
function searchPage(query: URLSearchParams): FakeRoute {
  const text = query.get('text')?.toLowerCase();
  if (text) {
    const found = PLACES.filter((p) => p.name.toLowerCase().includes(text));
    return html('Search', `<h1>Places</h1><ul>${listItems(found)}</ul>`);
  }
  const [west, south, east, north] = ['west', 'south', 'east', 'north'].map((name) =>
    Number(query.get(name))
  );
  const page = Number(query.get('page') ?? '1');
  const inside = PLACES.filter(
    (p) => p.lng >= west && p.lng <= east && p.lat >= south && p.lat <= north
  );
  const shown = inside.slice((page - 1) * 2, page * 2);
  const next = new URLSearchParams(query);
  next.set('page', String(page + 1));
  const more = inside.length > page * 2 ? `<a rel="next" href="/search?${next}">Next</a>` : '';
  return html('Search', `<h1>Places</h1><ul>${listItems(shown)}</ul>${more}`);
}
// @endif

/** Answers the fake browser's requests: a page, the availability JSON, or a 404 page. */
export function render{{PASCAL}}Site(url: URL): FakeRoute {
// @if search
  if (url.pathname === '/search') return searchPage(url.searchParams);
// @else
  if (url.pathname === '/places') return html('Our parks', `<h1>Our parks</h1><ul>${listItems(PLACES)}</ul>`);
// @endif
  if (url.pathname === '/api/availability') return availability(url.searchParams.get('place'));
  const match = /^\/places\/([^/]+)$/.exec(url.pathname);
  const place = match ? PLACES.find((p) => p.id === decodeURIComponent(match[1])) : undefined;
  return place ? placePage(place) : html('Not found', '<h1>Page not found</h1>', 404);
}
