/**
 * {{NAME}} (`src/main/providers/{{ID}}/`): the provider contract suite and what the module
 * reads from the pages, on the fake browser (`tests/utils/fake-browser.ts`). Its pages come from
 * the made-up site in `tests/fixtures/providers/{{ID}}/site.ts`, in jsdom, with the site's
 * script running: no real browser starts and nothing is sent anywhere.
 *
 * Generated by `npm run provider:new`. Keep it passing as the module grows, and replace the
 * made-up site (and the expectations below) with the real site's markup.
 */

import { ProviderHttpError } from '@main/providers/sdk';
import { ProviderRegistry } from '@main/providers/registry';
// @if search
import type { BoundingBox } from '@shared/types/catalog.types';
// @endif
import { isCalendarDate, type StayQuery } from '@shared/types/provider.types';
import { createFakeBrowser } from '@tests/utils/fake-browser';
import { createTestProviderContext } from '@tests/utils/fake-provider';
import { describeProviderContract } from '@tests/utils/provider-contract';
import { render{{PASCAL}}Site } from '@tests/fixtures/providers/{{ID}}/site';
import {
  {{CONST}}_SITE_URL,
  create{{PASCAL}}Factory,
  {{CAMEL}}Manifest,
} from '@main/providers/{{ID}}';

/** Any https address does: the fake browser answers from the made-up site. */
const SITE_URL = 'https://www.{{ID}}.test';
const STAY: StayQuery = { arrival: '2026-11-10', departure: '2026-11-12', adults: 2 };
// @if search
/** Western Australia, `[west, south, east, north]`. */
const WA: BoundingBox = [112, -36, 129, -13];
// @endif

describeProviderContract('{{ID}}', () => {
  const browser = createFakeBrowser(render{{PASCAL}}Site, { providerId: '{{ID}}' });
  const factory = create{{PASCAL}}Factory({ siteUrl: SITE_URL });
  return {
    provider: factory(createTestProviderContext(factory.manifest, { browser })),
    sample: { externalId: 'beach-house', stay: STAY },
    unknownExternalId: 'nowhere',
// @if search
    searchBbox: WA,
    searchText: 'Seabreeze',
// @endif
    // The suite checks that no call leaves a page open.
    openPages: browser.openPages,
  };
});

describe('{{NAME_JS}}', () => {
  const browser = createFakeBrowser(render{{PASCAL}}Site, { providerId: '{{ID}}' });
  // Registered in a fresh registry, as the app registers it.
  const registry = new ProviderRegistry();
  registry.register(create{{PASCAL}}Factory({ siteUrl: SITE_URL }), (manifest) =>
    createTestProviderContext(manifest, { browser })
  );
  const provider = registry.require('{{ID}}', 'availability');

// @if search
  it('searches a map area a page at a time, as LocationSummaries read from the pages', async () => {
    const first = await provider.catalog!.searchArea!({ bbox: WA });
    expect(first.items).toEqual([
      {
        key: '{{ID}}:beach-house',
        providerId: '{{ID}}',
        externalId: 'beach-house',
        name: 'Seabreeze Holiday Park',
        kind: 'holiday-park',
        bookingMode: 'online',
        lat: -33.6455,
        lng: 115.3459,
        area: { name: 'Busselton' },
        imageUrls: [],
        amenities: [],
        infoUrl: `${SITE_URL}/places/beach-house`,
      },
      expect.objectContaining({ key: '{{ID}}:karri-cabins', kind: 'cabin' }),
    ]);
    expect(first.nextCursor).toBe('2');
    const second = await provider.catalog!.searchArea!({ bbox: WA, cursor: first.nextCursor });
    // A word the mapping does not know is `other`.
    expect(second.items).toEqual([expect.objectContaining({ key: '{{ID}}:old-mill', kind: 'other' })]);
    expect(second.nextCursor).toBeUndefined();
  });

  it('searches by name', async () => {
    await expect(provider.catalog!.searchText!('Seabreeze')).resolves.toEqual([
      expect.objectContaining({ key: '{{ID}}:beach-house', name: 'Seabreeze Holiday Park' }),
    ]);
  });
// @else
  it('lists every place as a LocationSummary read from the pages', async () => {
    await expect(provider.catalog!.listLocations!()).resolves.toEqual([
      {
        key: '{{ID}}:beach-house',
        providerId: '{{ID}}',
        externalId: 'beach-house',
        name: 'Seabreeze Holiday Park',
        kind: 'holiday-park',
        bookingMode: 'online',
        lat: -33.6455,
        lng: 115.3459,
        area: { name: 'Busselton' },
        imageUrls: [],
        amenities: [],
        infoUrl: `${SITE_URL}/places/beach-house`,
      },
      expect.objectContaining({ key: '{{ID}}:karri-cabins', kind: 'cabin' }),
      // A word the mapping does not know is `other`.
      expect.objectContaining({ key: '{{ID}}:old-mill', kind: 'other' }),
    ]);
    expect(browser.visits).toContain(`${SITE_URL}/places`);
  });
// @endif

  it("reads a place's page: its units", async () => {
    await expect(provider.catalog!.getLocation('beach-house')).resolves.toMatchObject({
      key: '{{ID}}:beach-house',
      units: [
        { unitId: 'c1', unitName: 'Beach Cabin 1' },
        { unitId: 'c2', unitName: 'Garden Cabin 2' },
        { unitId: 'c3', unitName: 'Bunkhouse' },
      ],
    });
  });

  it("checks a stay with the site's own search form: only the stay's nights, never guessing", async () => {
    const result = await provider.availability.check('beach-house', STAY);
    expect(result.key).toBe('{{ID}}:beach-house');
    expect(result.units).toEqual([
      {
        unitId: 'c1',
        unitName: 'Beach Cabin 1',
        nights: [
          { date: '2026-11-10', state: 'available', price: 145 },
          { date: '2026-11-11', state: 'available', price: 155 },
        ],
        fullyAvailable: true,
      },
      {
        unitId: 'c2',
        unitName: 'Garden Cabin 2',
        nights: [
          { date: '2026-11-10', state: 'booked' },
          { date: '2026-11-11', state: 'available', price: 120 },
        ],
        fullyAvailable: false,
      },
      {
        // A word the mapping does not know is `unknown`, and so is a night the page left out.
        unitId: 'c3',
        unitName: 'Bunkhouse',
        nights: [
          { date: '2026-11-10', state: 'unknown' },
          { date: '2026-11-11', state: 'unknown' },
        ],
        fullyAvailable: false,
      },
    ]);
    for (const night of result.units.flatMap((unit) => unit.nights)) {
      expect(isCalendarDate(night.date)).toBe(true);
    }
    // The form's script asked the site for the stay: the page's own code ran.
    expect(browser.requests.map((request) => request.url)).toContain(
      `${SITE_URL}/api/availability?place=beach-house&arrival=2026-11-10&departure=2026-11-12&guests=2`
    );
    expect(browser.pageErrors).toEqual([]);
  });

  it('keeps only the units asked for', async () => {
    const result = await provider.availability.check('beach-house', STAY, { unitIds: ['c2'] });
    expect(result.units.map((unit) => unit.unitId)).toEqual(['c2']);
  });

  it('turns a missing page into a ProviderHttpError', async () => {
    await expect(provider.catalog!.getLocation('nowhere')).rejects.toBeInstanceOf(
      ProviderHttpError
    );
  });

  it('has an https address, or fails loudly and opens no page while it is a placeholder', async () => {
    if ({{CONST}}_SITE_URL) {
      expect({{CONST}}_SITE_URL).toMatch(/^https:\/\//);
      return;
    }
    const unsetBrowser = createFakeBrowser(render{{PASCAL}}Site, { providerId: '{{ID}}' });
    const unset = create{{PASCAL}}Factory()(
      createTestProviderContext({{CAMEL}}Manifest, { browser: unsetBrowser })
    );
    await expect(unset.catalog!.getLocation('beach-house')).rejects.toThrow(
      /set {{CONST}}_SITE_URL/
    );
    expect(unset.links.location('beach-house')).toBeNull();
    expect(unsetBrowser.visits).toEqual([]);
  });
});
