/**
 * {{NAME}}: a browser provider. Its website has no API, so the modules read its pages in the
 * person's installed Edge or Chrome through `ctx.browser`. Generated by `npm run provider:new`;
 * its manifest is in `manifest.ts`, what it reads from the pages in `pages.ts`.
 *
 * TODO before it ships:
 * - Read {{NAME}}'s terms of use and note here what they say about automated access. If they
 *   forbid it, the provider gets links only, not a browser module.
 * - Set {{CONST}}_SITE_URL below.
 * - Replace the paths, labels and attributes in `pages.ts` with the real site's, and the
 *   made-up site in `tests/fixtures/providers/{{ID}}/site.ts` with a trimmed copy of its
 *   markup (no personal details).
 *
 * Until the address is set, every call fails with a ProviderError that says so, no browser
 * starts, and the provider has no links.
 */

import type { Page } from 'playwright-core';
import type { LocationDetail } from '@shared/types/catalog.types';
import type { LocationAvailability } from '@shared/types/provider.types';
import { makeLocationKey } from '@shared/utils/location-key';
import {
  defineProvider,
  ProviderError,
  ProviderHttpError,
  ProviderParseError,
// @if search
  type CatalogAreaPage,
// @endif
  type ProviderContext,
  type ProviderFactory,
  type ProviderLinks,
} from '../sdk';
import { {{CAMEL}}Manifest } from './manifest';
import {
// @if search
  isInside,
// @endif
  readPlaces,
  readRows,
  readUnits,
  SITE,
  toLocationSummary,
  toUnitAvailability,
} from './pages';

export { {{CAMEL}}Manifest } from './manifest';

/** TODO: the website's https address, such as `https://www.example.com`. */
export const {{CONST}}_SITE_URL = '';

export interface {{PASCAL}}Options {
  /** The website's address: {{CONST}}_SITE_URL unless a test gives another. */
  siteUrl?: string;
}

export function create{{PASCAL}}Factory({
  siteUrl = {{CONST}}_SITE_URL,
}: {{PASCAL}}Options = {}): ProviderFactory {
  return defineProvider({{CAMEL}}Manifest, (ctx: ProviderContext) => {
    /** An address on the site, or a loud error while the site's address is a placeholder. */
    function siteUrlFor(path: string): string {
      if (!siteUrl) {
        throw new ProviderError({
          providerId: ctx.id,
          message: `${ctx.manifest.name} is not set up yet: set {{CONST}}_SITE_URL in src/main/providers/{{ID}}/index.ts`,
        });
      }
      return `${siteUrl.replace(/\/+$/, '')}${path}`;
    }

    /**
     * Runs `fn` on a fresh page: one unit of work per call, and an abort closes the page. The
     * site's address is checked first, so a placeholder never starts a browser.
     */
    async function withPage<T>(
      signal: AbortSignal | undefined,
      fn: (page: Page) => Promise<T>
    ): Promise<T> {
      siteUrlFor('/');
      return ctx.browser.withPage(fn, { signal });
    }

    /** Opens `path`, and turns an error page into an error: a page without data is not empty. */
    async function open(page: Page, path: string): Promise<void> {
      const url = siteUrlFor(path);
      const response = await page.goto(url, { waitUntil: 'domcontentloaded' });
      const status = response?.status() ?? 0;
      if (status < 200 || status >= 300) {
        throw new ProviderHttpError({ providerId: ctx.id, status, url });
      }
    }

    const links: ProviderLinks = {
      // TODO: the provider's own page for a place, and its booking page.
      location: (externalId) => (siteUrl ? siteUrlFor(SITE.placePath(externalId)) : null),
      booking: (externalId) => (siteUrl ? siteUrlFor(`${SITE.placePath(externalId)}/book`) : null),
    };

    return {
      links,
      catalog: {
// @if search
        // One results page per call: the app follows `nextCursor` for a few pages, and keeps
        // what it finds. The cursor is the site's page number, as a string.
        searchArea: ({ bbox, cursor }, signal) =>
          withPage(signal, async (page): Promise<CatalogAreaPage> => {
            const [west, south, east, north] = bbox;
            const pageNumber = cursor ? Number(cursor) : 1;
            const query = new URLSearchParams({
              west: String(west),
              south: String(south),
              east: String(east),
              north: String(north),
              page: String(pageNumber),
            });
            await open(page, `${SITE.searchPath}?${query}`);
            const items = (await page.$$eval(SITE.place, readPlaces))
              // Only the places inside the area, whatever the page shows.
              .filter((place) => isInside(bbox, place))
              .map((place) => toLocationSummary(ctx.id, place, links));
            const more = (await page.locator(SITE.nextPage).count()) > 0;
            return more ? { items, nextCursor: String(pageNumber + 1) } : { items };
          }),
        // Optional: the site's search by name, for a name someone types into Explore's "Where"
        // or a watch's location step (3 characters or more). One page visit, the best few
        // dozen matches. If the site cannot search by name, delete it: the location step then
        // suggests browsing the provider's places on the Explore map instead.
        searchText: (text, signal) =>
          withPage(signal, async (page) => {
            await open(page, `${SITE.searchPath}?${new URLSearchParams({ text })}`);
            const places = await page.$$eval(SITE.place, readPlaces);
            return places.map((place) => toLocationSummary(ctx.id, place, links));
          }),
// @else
        listLocations: (signal) =>
          withPage(signal, async (page) => {
            await open(page, SITE.listPath);
            const places = await page.$$eval(SITE.place, readPlaces);
            return places.map((place) => toLocationSummary(ctx.id, place, links));
          }),
// @endif
        getLocation: (externalId, signal) =>
          withPage(signal, async (page): Promise<LocationDetail> => {
            await open(page, SITE.placePath(externalId));
            const [place] = await page.$$eval(`main${SITE.place}`, readPlaces);
            if (!place) {
              throw new ProviderParseError({
                providerId: ctx.id,
                message: `${ctx.id}: no place on ${SITE.placePath(externalId)}`,
              });
            }
            const units = await page.$$eval(SITE.unit, readUnits);
            return {
              ...toLocationSummary(ctx.id, place, links),
              units,
              fetchedAt: ctx.clock().toISOString(),
            };
          }),
      },
      availability: {
        check: (externalId, stay, options = {}) =>
          withPage(options.signal, async (page): Promise<LocationAvailability> => {
            await open(page, SITE.placePath(externalId));
            // The place page's own search form: the site's script asks for the nights and
            // draws them. Locators wait for each field; wait for the results, never a time.
            await page.getByLabel(SITE.arrival).fill(stay.arrival);
            await page.getByLabel(SITE.departure).fill(stay.departure);
            await page.getByLabel(SITE.guests).fill(String(stay.adults + (stay.children ?? 0)));
            await page.getByRole('button', { name: SITE.check }).click();
            await page.locator(SITE.results).waitFor();
            const rows = await page.$$eval(SITE.resultRow, readRows);
            const wanted = options.unitIds?.length ? new Set(options.unitIds) : undefined;
            return {
              key: makeLocationKey(ctx.id, externalId),
              checkedAt: ctx.clock().toISOString(),
              units: rows
                .filter((row) => !wanted || wanted.has(row.unitId))
                .map((row) => toUnitAvailability(stay, row)),
              bookingUrl: links.booking(externalId, stay) ?? undefined,
            };
          }),
      },
    };
  });
}

/** What `BUILT_IN_PROVIDERS` in `src/main/providers/index.ts` registers. */
export const {{CAMEL}}Factory = create{{PASCAL}}Factory();
