/**
 * {{NAME}}: who the provider is and what it can do. The registry validates this manifest, and
 * the renderer and the core services read everything about the provider from it: no other code
 * in the app names it.
 *
 * Generated by `npm run provider:new`. Resolve every TODO before it ships: see "Adding a
 * provider" in CLAUDE.md and docs/providers/adding-a-provider.md.
 */

import type { ProviderManifest } from '@shared/types/provider.types';

export const {{CAMEL}}Manifest: ProviderManifest = {
  // Stored in every watch, snipe, booking and notification, so it never changes once shipped.
  id: '{{ID}}',
  // TODO: the provider's own name, for pickers and badges. `shortName` (24 characters at most)
  // also starts its desktop notifications.
  name: '{{NAME_JS}}',
  shortName: '{{SHORT_NAME_JS}}',
  // TODO: one line, shown in the provider step of the create flows.
  description: 'Places to stay from {{NAME_JS}}.',
  // TODO: the provider's https home page. A `.invalid` address never resolves.
  website: 'https://{{ID}}.invalid',
// @if api
  // `api`: every module talks to the provider through `ctx.http`.
  integration: 'api',
// @else
  // `browser`: the modules read the provider's website through `ctx.browser` (it has no API).
  integration: 'browser',
// @endif
  // A coloured monogram badge, never a third-party logo. White text on this colour passes AA.
  brand: { color: '{{COLOR}}', monogram: '{{MONOGRAM}}' },
  // TODO: every kind of place the provider has. Each location's `kind` must be one of these.
// @if api
  locationKinds: ['campground', 'cabin', 'other'],
// @else
  locationKinds: ['holiday-park', 'cabin', 'other'],
// @endif
  // The time zone of the provider's dates and release times, and the currency of its prices.
  timezone: 'Australia/Perth',
  currency: 'AUD',
  capabilities: {
    // Explore's map and list, and each place's page: `catalog.getLocation`, plus
    // `catalog.listLocations` (`full`) or `catalog.searchArea` (`search`).
    catalog: true,
// @if search
    // `search`: the catalogue is too big to list. The app asks `catalog.searchArea` for the
    // map area Explore shows (a few pages at most) and keeps what it finds.
    catalogMode: 'search',
// @else
    // `full`: `catalog.listLocations` lists every place, and the app syncs the list every
    // `catalogTtlHours`. A marketplace too big to list uses `search` instead.
    catalogMode: 'full',
// @endif
    // "Check availability" on a place's page: `availability.check`.
    availability: true,
    // Free counts on Explore's pins and cards: `availability.search`, every place in one call.
    bulkAvailability: false,
    // The provider in Watches: `availability.check`.
    watches: true,
    // Site Sniper: needs holds, availability, a release policy and `releaseModes`.
    snipes: false,
    // Automatic holds and the payment window: `holds.create` and `holds.paymentUrl`.
    holds: false,
    // "Import booking" on the Bookings page: `bookings.get`.
    bookingImport: false,
    // A waiting room or queue in front of the provider: an `access` module.
    accessGate: false,
    // 'none', 'optional', 'required-for-holds' or 'required'. Anything but 'none' needs `auth`.
    account: 'none',
  },
// @if api
  // How hard the app may use the provider. TODO: set them for the provider's capacity.
// @if search
  // `catalogTtlHours` is how long the app waits before it searches the same area again.
// @endif
  limits: { minWatchIntervalMinutes: 30, maxConcurrentRequests: 2, catalogTtlHours: 24 },
// @else
  // A page visit costs the site far more than an API call: one page at a time, and rarely.
// @if search
  // `catalogTtlHours` is how long the app waits before it searches the same area again.
// @endif
  limits: { minWatchIntervalMinutes: 60, maxConcurrentRequests: 1, catalogTtlHours: 72 },
// @endif
};
