#!/usr/bin/env python3
"""
One-off design step: outline the WA Stay wordmark and banner text into scripts/brand/glyphs.json.

The brand SVGs must not contain <text> (they would depend on installed fonts), so the words are
converted to path outlines once and committed. scripts/brand/logo.js reads glyphs.json; nothing
in the build or CI runs this file. Re-run it only when the wording, face or weight changes.

Fonts are the ones the app already bundles (node_modules/@fontsource-variable), shaped with
HarfBuzz so kerning matches the live text:
  - Fraunces (SIL OFL 1.1), opsz/wght build: the D1 display face, for the wordmark.
  - Figtree (SIL OFL 1.1): the D1 UI face, for the banner tagline.
Outlining an OFL font inside a logo is permitted by the licence (the font itself is not
redistributed).

Requires Python 3 with fonttools, brotli and uharfbuzz:
  pip install fonttools brotli uharfbuzz
  python3 scripts/brand/outline-text.py
"""
import io
import json
import os

import uharfbuzz as hb
from fontTools.pens.basePen import BasePen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
FONTS = os.path.join(ROOT, 'node_modules', '@fontsource-variable')
OUT = os.path.join(ROOT, 'scripts', 'brand', 'glyphs.json')

# Every string is set at 100 units per em, baseline at y = 0, y pointing down (SVG space).
SIZE = 100
TEXTS = {
    'wordmark': {
        'text': 'WA Stay',
        'family': 'Fraunces',
        'file': 'fraunces/files/fraunces-latin-opsz-normal.woff2',
        'axes': {'wght': 600, 'opsz': 72},
    },
    'monogram': {
        'text': 'WA',
        'family': 'Fraunces',
        'file': 'fraunces/files/fraunces-latin-opsz-normal.woff2',
        'axes': {'wght': 700, 'opsz': 72},
    },
    'tagline': {
        'text': 'Places to stay across Western Australia',
        'family': 'Figtree',
        'file': 'figtree/files/figtree-latin-wght-normal.woff2',
        'axes': {'wght': 500},
    },
}


def num(v):
    s = '%.2f' % v
    s = s.rstrip('0').rstrip('.')
    return '0' if s in ('-0', '') else s


class PathPen(BasePen):
    """Absolute M/L/Q/C/Z commands only, so logo.js can transform them with a tiny parser."""

    def __init__(self):
        super().__init__(None)
        self.parts = []

    def _moveTo(self, p):
        self.parts.append('M%s %s' % (num(p[0]), num(p[1])))

    def _lineTo(self, p):
        self.parts.append('L%s %s' % (num(p[0]), num(p[1])))

    def _qCurveToOne(self, p1, p2):
        self.parts.append('Q%s %s %s %s' % (num(p1[0]), num(p1[1]), num(p2[0]), num(p2[1])))

    def _curveToOne(self, p1, p2, p3):
        self.parts.append(
            'C%s %s %s %s %s %s'
            % (num(p1[0]), num(p1[1]), num(p2[0]), num(p2[1]), num(p3[0]), num(p3[1]))
        )

    def _closePath(self):
        self.parts.append('Z')

    def _endPath(self):
        pass


def outline(spec):
    tt = TTFont(os.path.join(FONTS, spec['file']))
    tt.flavor = None
    data = io.BytesIO()
    tt.save(data)
    face = hb.Face(data.getvalue())
    font = hb.Font(face)
    font.set_variations(spec['axes'])
    scale = SIZE / face.upem

    buf = hb.Buffer()
    buf.add_str(spec['text'])
    buf.guess_segment_properties()
    hb.shape(font, buf, {'kern': True, 'liga': True})

    pen = PathPen()
    x = 0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        dx = (x + pos.x_offset) * scale
        dy = -pos.y_offset * scale
        font.draw_glyph_with_pen(info.codepoint, TransformPen(pen, (scale, 0, 0, -scale, dx, dy)))
        x += pos.x_advance

    os2 = tt['OS/2']
    return {
        'text': spec['text'],
        'family': spec['family'],
        'axes': spec['axes'],
        'advance': round(x * scale, 2),
        'capHeight': round(os2.sCapHeight * scale, 2),
        'xHeight': round(os2.sxHeight * scale, 2),
        'd': ''.join(pen.parts),
    }


def main():
    out = {
        'note': 'Generated by scripts/brand/outline-text.py. Do not edit by hand.',
        'unitsPerEm': SIZE,
        'texts': {key: outline(spec) for key, spec in TEXTS.items()},
    }
    with open(OUT, 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=2)
        f.write('\n')
    print('wrote', os.path.relpath(OUT, ROOT))


if __name__ == '__main__':
    main()
