-- WA ParkStay Bookings v1.2.0 database (schema v5)
-- Schema version 5, generated from connection.ts at dcccfa72a5c89f13aaec3c78f207e3e8ffc90147.
-- Generated by tests/fixtures/db/generate.ts. Do not edit by hand: regenerate instead.
BEGIN TRANSACTION;
CREATE TABLE users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      email TEXT UNIQUE NOT NULL,
      encrypted_password TEXT NOT NULL,
      encryption_key TEXT NOT NULL,
      encryption_iv TEXT NOT NULL,
      encryption_auth_tag TEXT NOT NULL,
      first_name TEXT,
      last_name TEXT,
      phone TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );
INSERT INTO "users" VALUES(1,'fixture.user@example.com','d5b7c34dbee450315d73bd87dbf1b89ef8c3','5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c5c','0f1e2d3c4b5a69788796a5b4c3d2e1f0','b889d33dd8ecac43aa4d16ab67965eae','Fixture','User','+61400000000','2025-11-02 01:00:00','2025-11-02 01:00:00');
CREATE TABLE bookings (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      booking_reference TEXT UNIQUE NOT NULL,
      park_name TEXT NOT NULL,
      campground_name TEXT NOT NULL,
      site_number TEXT,
      site_type TEXT,
      arrival_date DATE NOT NULL,
      departure_date DATE NOT NULL,
      num_nights INTEGER NOT NULL,
      num_guests INTEGER NOT NULL,
      total_cost DECIMAL(10,2),
      currency TEXT DEFAULT 'AUD',
      status TEXT NOT NULL CHECK(status IN ('confirmed', 'cancelled', 'pending')),
      booking_data JSON,
      notes TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      synced_at DATETIME,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  );
INSERT INTO "bookings" VALUES(1,1,'PS0012345','Cape Range National Park','Osprey Bay','12','Unpowered','2026-01-10T00:00:00.000Z','2026-01-13T00:00:00.000Z',3,2,85.5,'AUD','confirmed','{"gearType":"tent","vehicles":1}','Ocean-side site','2025-11-03 02:00:00','2025-11-03 02:00:00','2025-11-03 02:05:00');
INSERT INTO "bookings" VALUES(2,1,'PS0067890','Cape Le Grand National Park','Lucky Bay',NULL,NULL,'2026-03-20T00:00:00.000Z','2026-03-22T00:00:00.000Z',2,4,NULL,'AUD','cancelled',NULL,NULL,'2025-11-04 03:00:00','2025-11-05 03:00:00',NULL);
CREATE TABLE watches (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      park_id TEXT NOT NULL,
      park_name TEXT NOT NULL,
      campground_id TEXT NOT NULL,
      campground_name TEXT NOT NULL,
      arrival_date DATE NOT NULL,
      departure_date DATE NOT NULL,
      num_guests INTEGER NOT NULL,
      preferred_sites JSON,
      site_type TEXT,
      check_interval_minutes INTEGER DEFAULT 5,
      is_active BOOLEAN DEFAULT 1,
      last_checked_at DATETIME,
      next_check_at DATETIME,
      last_result TEXT,
      found_count INTEGER DEFAULT 0,
      auto_book BOOLEAN DEFAULT 0,
      notify_only BOOLEAN DEFAULT 1,
      max_price DECIMAL(10,2),
      notes TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, last_availability JSON, allow_partial_match BOOLEAN DEFAULT 0,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  );
INSERT INTO "watches" VALUES(1,1,'Osprey Bay Easter','17','Cape Range National Park','34','Osprey Bay','2026-04-03T00:00:00.000Z','2026-04-06T00:00:00.000Z',2,'["136","137"]','Unpowered',15,1,'2025-11-06 04:00:00','2025-11-06 04:15:00','found',2,0,1,60,NULL,'2025-11-05 04:00:00','2025-11-06 04:00:00','[{"siteId":"136","siteName":"Site 136","siteType":"Unpowered","available":true,"price":20,"dates":[{"date":"2026-04-03","available":true,"price":20}]}]',1);
INSERT INTO "watches" VALUES(2,1,'Lucky Bay long weekend','42','Cape Le Grand National Park','88','Lucky Bay','2026-06-01T00:00:00.000Z','2026-06-03T00:00:00.000Z',4,NULL,NULL,60,0,NULL,NULL,NULL,0,0,1,NULL,'Paused','2025-11-07 05:00:00','2025-11-07 05:00:00',NULL,0);
CREATE TABLE skip_the_queue_entries (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      booking_id INTEGER NOT NULL,
      booking_reference TEXT NOT NULL,
      is_active BOOLEAN DEFAULT 1,
      check_interval_minutes INTEGER DEFAULT 2,
      last_checked_at DATETIME,
      next_check_at DATETIME,
      attempts_count INTEGER DEFAULT 0,
      max_attempts INTEGER DEFAULT 1000,
      last_result TEXT,
      success_date DATETIME,
      new_booking_reference TEXT,
      notes TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE
  );
INSERT INTO "skip_the_queue_entries" VALUES(1,1,1,'PS0012345',0,2,'2025-11-04 03:29:00',NULL,41,1000,'success','2025-11-04 03:29:00','PS0012399',NULL,'2025-11-03 02:10:00','2025-11-04 03:29:00');
CREATE TABLE notifications (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      type TEXT NOT NULL CHECK(type IN ('watch_found', 'stq_success', 'booking_confirmed', 'error', 'warning', 'info')),
      title TEXT NOT NULL,
      message TEXT NOT NULL,
      related_id INTEGER,
      related_type TEXT CHECK(related_type IN ('booking', 'watch', 'stq')),
      action_url TEXT,
      is_read BOOLEAN DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  );
INSERT INTO "notifications" VALUES(1,1,'watch_found','Availability found','Osprey Bay has 2 sites free',1,'watch',NULL,0,'2025-11-06 04:00:01');
INSERT INTO "notifications" VALUES(2,1,'info','Welcome','ParkStay Bookings is ready',NULL,NULL,NULL,1,'2025-11-02 01:00:01');
INSERT INTO "notifications" VALUES(3,1,'stq_success','Rebooked','Skip The Queue rebooked PS0012345',1,'stq',NULL,1,'2025-11-04 03:30:00');
CREATE TABLE job_logs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      job_type TEXT NOT NULL CHECK(job_type IN ('watch_poll', 'stq_check', 'cleanup')),
      job_id INTEGER NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('success', 'failure', 'error')),
      message TEXT,
      error_details TEXT,
      duration_ms INTEGER,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );
CREATE TABLE settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL,
      value_type TEXT NOT NULL CHECK(value_type IN ('string', 'number', 'boolean', 'json')),
      category TEXT NOT NULL,
      description TEXT,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );
INSERT INTO "settings" VALUES('launchOnStartup','true','boolean','general',NULL,'2025-11-02 01:20:00');
INSERT INTO "settings" VALUES('defaultCheckIntervalMinutes','15','number','watches','Default watch interval','2025-11-02 01:20:00');
INSERT INTO "settings" VALUES('dashboardLayout','{"cards":["watches","bookings"]}','json','ui',NULL,'2025-11-02 01:20:00');
CREATE TABLE migrations (
      version INTEGER PRIMARY KEY,
      applied_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
INSERT INTO "migrations" VALUES(1,'2025-11-01 00:00:00');
INSERT INTO "migrations" VALUES(2,'2025-11-01 00:00:00');
INSERT INTO "migrations" VALUES(3,'2025-11-01 00:00:00');
INSERT INTO "migrations" VALUES(4,'2025-11-01 00:00:00');
INSERT INTO "migrations" VALUES(5,'2025-11-01 00:00:00');
CREATE TABLE notification_providers (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        channel TEXT NOT NULL UNIQUE,
        display_name TEXT NOT NULL,
        enabled BOOLEAN DEFAULT 0,
        config JSON NOT NULL,
        status TEXT DEFAULT 'not_configured',
        last_tested_at DATETIME,
        last_error TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
      );
INSERT INTO "notification_providers" VALUES(1,'email_smtp','Email (SMTP)',1,'a0b1c2d3e4f5061728394a5b6c7d8e9f:e1a1460983e80e1efbb4b81f8621b80a:09afde8c506134c432e0a936ae03e348ad9bdab40facf44132e4fc07c2a62916a5e71c0945fefc0e2f6b24076f48eb24c105f8a86776676c13886b77f0ade55325b74ce8df0cc48a9aa3f5ea9ed0f3b64546f1049811f2920360b5de5568ec4bff0d100a9eddcdd497a42a217fbf06f6bbd8b69f2f007a3266030388ed23acc684de5da82f0644cba4440536812c59b0ce9c59fd1b7d1bacb00615271b02a0c5a9626e071db7097ee362b9499513fc33406ab286963309','configured','2025-11-02 01:10:00',NULL,'2025-11-02 01:05:00','2025-11-02 01:10:00');
CREATE TABLE notification_delivery_logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        notification_id INTEGER,
        provider_channel TEXT NOT NULL,
        status TEXT NOT NULL,
        message_id TEXT,
        error_message TEXT,
        sent_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (notification_id) REFERENCES notifications(id)
      );
INSERT INTO "notification_delivery_logs" VALUES(1,1,'email_smtp','sent','<fixture-1@example.com>',NULL,'2025-11-06T04:00:02.000Z','2025-11-06 04:00:02');
INSERT INTO "notification_delivery_logs" VALUES(2,NULL,'email_smtp','failed',NULL,'Invalid login',NULL,'2025-11-04 03:30:01');
CREATE TABLE queue_session (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        session_key TEXT NOT NULL,
        status TEXT DEFAULT 'Unknown',
        position INTEGER DEFAULT 0,
        estimated_wait_seconds INTEGER DEFAULT 0,
        expiry_seconds INTEGER DEFAULT 0,
        expires_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
      );
INSERT INTO "queue_session" VALUES(1,'FIXTURESESSIONKEY00000000000000000000000000000000000','Active',0,0,600,'2025-11-06T04:10:00.000Z','2025-11-06T04:00:00.000Z','2025-11-06T04:00:00.000Z');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('bookings',2);
INSERT INTO sqlite_sequence VALUES('watches',2);
INSERT INTO sqlite_sequence VALUES('notifications',3);
INSERT INTO sqlite_sequence VALUES('notification_providers',1);
INSERT INTO sqlite_sequence VALUES('notification_delivery_logs',2);
INSERT INTO sqlite_sequence VALUES('skip_the_queue_entries',1);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_bookings_user_id ON bookings(user_id);
CREATE INDEX idx_bookings_reference ON bookings(booking_reference);
CREATE INDEX idx_bookings_status ON bookings(status);
CREATE INDEX idx_bookings_arrival_date ON bookings(arrival_date);
CREATE INDEX idx_bookings_dates ON bookings(arrival_date, departure_date);
CREATE INDEX idx_watches_user_id ON watches(user_id);
CREATE INDEX idx_watches_active ON watches(is_active);
CREATE INDEX idx_watches_next_check ON watches(next_check_at);
CREATE INDEX idx_watches_dates ON watches(arrival_date, departure_date);
CREATE INDEX idx_stq_user_id ON skip_the_queue_entries(user_id);
CREATE INDEX idx_stq_booking_id ON skip_the_queue_entries(booking_id);
CREATE INDEX idx_stq_active ON skip_the_queue_entries(is_active);
CREATE INDEX idx_stq_next_check ON skip_the_queue_entries(next_check_at);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);
CREATE INDEX idx_notifications_type ON notifications(type);
CREATE INDEX idx_notifications_created_at ON notifications(created_at);
CREATE INDEX idx_job_logs_type ON job_logs(job_type);
CREATE INDEX idx_job_logs_job_id ON job_logs(job_id);
CREATE INDEX idx_job_logs_status ON job_logs(status);
CREATE INDEX idx_job_logs_created_at ON job_logs(created_at);
CREATE INDEX idx_settings_category ON settings(category);
CREATE INDEX idx_notification_providers_channel ON notification_providers(channel);
CREATE INDEX idx_notification_providers_enabled ON notification_providers(enabled);
CREATE INDEX idx_delivery_logs_notification_id ON notification_delivery_logs(notification_id);
CREATE INDEX idx_delivery_logs_provider ON notification_delivery_logs(provider_channel);
CREATE INDEX idx_delivery_logs_status ON notification_delivery_logs(status);
CREATE INDEX idx_delivery_logs_created_at ON notification_delivery_logs(created_at);
CREATE TRIGGER update_users_timestamp
  AFTER UPDATE ON users
  BEGIN
      UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
  END;
CREATE TRIGGER update_bookings_timestamp
  AFTER UPDATE ON bookings
  BEGIN
      UPDATE bookings SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
  END;
CREATE TRIGGER update_watches_timestamp
  AFTER UPDATE ON watches
  BEGIN
      UPDATE watches SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
  END;
CREATE TRIGGER update_stq_timestamp
  AFTER UPDATE ON skip_the_queue_entries
  BEGIN
      UPDATE skip_the_queue_entries SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
  END;
CREATE TRIGGER update_settings_timestamp
  AFTER UPDATE ON settings
  BEGIN
      UPDATE settings SET updated_at = CURRENT_TIMESTAMP WHERE key = NEW.key;
  END;
COMMIT;
