import lockupUrl from '../../assets/brand/logo-lockup.svg';
import markUrl from '../../assets/brand/logo-mark.svg';

/**
 * The WA Stay logo. The artwork is generated by `npm run icons` from scripts/brand/logo.js and
 * copied here from resources/brand; never edit the SVGs by hand.
 *
 * - `lockup`: the mark with the "WA Stay" wordmark, for the app header and About.
 * - `mark`: the square mark on its sand plate, for tight spaces.
 *
 * Usage rules (resources/brand/README.md): keep clear space around it, and never go below
 * 16 px for the mark or 96 px wide for the lockup.
 */
export type LogoVariant = 'mark' | 'lockup';

export interface LogoProps {
  variant: LogoVariant;
  /** Hide it from assistive technology when the brand name is already said next to it. */
  decorative?: boolean;
  /** Sizing utilities. Replaces the default size (32 px high), so give a height. */
  className?: string;
}

const SOURCES: Record<LogoVariant, string> = { mark: markUrl, lockup: lockupUrl };

/** Spacing-scale sizes: the lockup keeps its own aspect ratio from the SVG viewBox. */
const DEFAULT_SIZE: Record<LogoVariant, string> = { mark: 'h-8 w-8', lockup: 'h-8 w-auto' };

export function Logo({ variant, decorative = false, className }: LogoProps) {
  return (
    <img
      src={SOURCES[variant]}
      alt={decorative ? '' : 'WA Stay'}
      aria-hidden={decorative ? true : undefined}
      draggable={false}
      className={className ?? DEFAULT_SIZE[variant]}
    />
  );
}

export default Logo;
